#!/bin/bash

# Tests for the file interpreting interface of subs

function assert_equal()
{
    if [ "$1" != "$2" ]; then
    {
        echo "Assert failed: '"$1"' != '"$2"'."
        exit 1
    }; fi
}

# If the file doesn't exist we should fail
./subs nonexistentfile 2> /dev/null && exit 1

assert_equal `./subs testslow/fifteen.scm` "15"

assert_equal `./subs testslow/two_plus_three.scm` "5"

assert_equal `echo "(- 12 3)" | ./subs -` "9"

