#!/bin/bash

# Tests for the file interpreting interface of subs

function assert_equal()
{
    if [ "$1" != "$2" ]; then
    {
        echo "Assert failed: '"$1"' != '"$2"'."
        exit 1
    }; fi
}

# If we try to run a file that doesn't exist we should fail
./subs nonexistentfile 2> /dev/null && exit 1

# If we run an empty file we succeed
./subs testslow/empty.scm 2> /dev/null || exit 1

# If we try to do a session-test with a file that doesn't exist we should fail
./subs --session-test nonexistentfile 2> /dev/null && exit 1

# If we try to do a session-test with an empty file we should fail
./subs --session-test testslow/empty.scmsession 2> /dev/null && exit 1

# If we do a session-test that is incorrect we should fail
./subs --session-test testslow/incorrect.scmsession 2> /dev/null && exit 1
./subs --session-test testslow/incorrect_later.scmsession 2> /dev/null && exit 1

# Basic running a file
assert_equal `./subs testslow/fifteen.scm` "15"
assert_equal `./subs testslow/two_plus_three.scm` "5"

# FAILS: Basic running a file containing multiple lines
#assert_equal `./subs testslow/multiple_lines.scm` "-1"

# Running from stdin
assert_equal `echo "(- 12 3)" | ./subs -` "9"

